### ISSUE TITLE
MELPA

### ISSUE THREAD

**Issue by michalrus** [cajetanus/gregorio-mode.el#7]
@cajetanus, could you add this to MELPA?

**Comment by cajetanus** [comment]
Dear Michal,

Certainly, I would be glad to. I simply use el-get now as it works for
me.

I am about to finish a major upgrade to the package to align with the
release of gregorio 4.0. I hope to provide syntax coloring for the nabc
"dialect" and to provide some functions to auto-separate syllables and
integrate with the new way that gregorio is doing things with
--shell-escape and the like. I plan to have it more integrated with
auctex so that people can work on the master document and the gabc at
the same time.

I'm not pushing anything to github yet as most people are on greg 3.0
and it would just cause confusion as the docs will change a lot for the
new release - especially with regard to the master file. I thought it
best to keep it like it is while I am working with the beta, and push
all changes when gregorio itself goes final.

However if you want the version asap I could sign over the present
branch. How soon do you need it on melpa?

JJ +

-----Original Message-----
From: Michal Rus
Sent: 10/20/2015 08:09:09 PM


@cajetanus, could you add this to MELPA?

---
Reply to this email directly or view it on GitHub:
https://github.com/cajetanus/gregorio-mode.el/issues/7

**Comment by cajetanus** [comment]
I just contributed the recipe to melpa, it passes the travis build tests. They just need to approve it but everything is there.

**Comment by cajetanus** [comment]
reopening issue so as to make package more in conformity with MELPA guidelines.

**Comment by michalrus** [comment]
Brother Cajetanus,

I’m very thrilled with your reply, with your feedback and commitment. The open source world could really benefit from more clerics in the community. :heart: I took the liberty of showing your response to some of my friends, one of whom said that if priests are using Emacs, he might even reconvert.

Thank you for taking your time to put it up on MELPA. I’ve been sourcing all packages in my config from there, but maybe this is a good occasion for me to take a look at el-get (which I did).

Laudetur Iesus Christus!

**Comment by cajetanus** [comment]
Dear Michal,

I already sent a commit, but I need to do some modifications so that it
fits the MELPA conventions. I will work on this tomorrow as I have quite
a few things to finish today.

You could pull my fork of MELPA if you need it right away, as it has
checked in with the build server.

Or even easier would simply to manually add the recipe file to your own
copy of MELPA. It is under recipe/gregorio-mode

JJ +

-----Original Message-----
From: Michal Rus
Sent: 10/21/2015 10:51:29 AM


Brother Cajetanus,

I’m very thrilled with your reply, with your feedback and commitment. The open source world could really benefit from more clerics in the community. :heart: I took the liberty of showing your response to some of my friends, one of whom said that if priests are using Emacs, he might even reconvert.

Thank you for taking your time to put it up on MELPA. I’ve been sourcing all packages in my config from there, but maybe this is a good occasion for me to take a look at el-get (which I did).

Laudetur Iesus Christus!

---

**Comment by cajetanus** [comment]
The recipe was formally added to MELPA with the pull request:
https://github.com/milkypostman/melpa/pull/3237
It is thus in the MELPA package manager and can be used immediately.

However we must state that there will be some changes to the keyboard shortcuts in the next version in order to comply with MELPA guidelines. Also there will be some changes to follow the development of gregorio-4.0

JJ+

**Comment by michalrus** [comment]
@cajetanus, thank you very much. :heart:
